<a href="https://colab.research.google.com/github/marianecosta/dados-opcoes-acoes/blob/main/DadosOpcoesNet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import requests

In [ ]:
def listar_opcoes(ativo_obj, vencimento):
  url = f'https://opcoes.net.br/listaopcoes/completa?idAcao={ativo_obj}&listarVencimentos=false&cotacoes=true&vencimentos={vencimento}'
  r = requests.get(url).json()
  l = [[ativo_obj, vencimento, i[0].split('_')[0], i[2], i[3], i[4], i[5], i[8], i[9], i[10]] for i in r['data']['cotacoesOpcoes']]
  return pd.DataFrame(l, columns=['ativo_obj', 'Vencimento', 'Ticker', 'Tipo', 'Modelo', 'A/I/OTM','Strike', 'Preço', 'N. de negócios', 'Volume Neg.'])

In [ ]:
def listar_tudo(ativo_obj):
  url=f'https://opcoes.net.br/listaopcoes/completa?idAcao={ativo_obj}&listarVencimentos=true&cotacoes=true'
  r = requests.get(url).json()
  vencimentos = [i['value'] for i in r['data']['vencimentos']]
  df = pd.concat([listar_opcoes(ativo_obj, vencimento) for vencimento in vencimentos])
  return df

In [ ]:
listar_tudo('PETR4')

,ativo_obj,Vencimento,Ticker,Tipo,Modelo,A/I/OTM,Strike,Preço,N. de negócios,Volume Neg.
0,PETR4,2022-07-15,PETRG1,CALL,A,ITM,13.44,14.62,12.0,17555.0
1,PETR4,2022-07-15,PETRG2,CALL,A,ITM,13.94,14.95,1.0,59800.0
2,PETR4,2022-07-15,PETRG3,CALL,A,ITM,14.44,13.70,1.0,13700.0
3,PETR4,2022-07-15,PETRG4,CALL,A,ITM,15.44,12.69,1.0,12690.0
4,PETR4,2022-07-15,PETRG5,CALL,A,ITM,18.44,10.10,11.0,56035.0
...,...,...,...,...,...,...,...,...,...,...
15,PETR4,2024-04-19,PETRP299,PUT,E,ITM,29.93,3.45,2.0,37950.0
16,PETR4,2024-04-19,PETRP303,PUT,E,OTM,26.43,2.55,2.0,10510.0
17,PETR4,2024-04-19,PETRP307,PUT,E,OTM,27.18,2.21,6.0,5481.0
18,PETR4,2024-04-19,PETRP369,PUT,E,ITM,30.43,3.63,12.0,26070.0
19,PETR4,2024-04-19,PETRP550,PUT,E,ITM,51.43,17.24,1.0,17240.0

In [ ]:
aux = listar_tudo('PETR4')

# Procura opções com vencimento em 2022-07-15 e com número de negócios maior que 700
aux[(aux['Vencimento'] == '2022-07-15') & (aux['N. de negócios'] > 700)]

,ativo_obj,Vencimento,Ticker,Tipo,Modelo,A/I/OTM,Strike,Preço,N. de negócios,Volume Neg.
41,PETR4,2022-07-15,PETRG247,CALL,A,OTM,29.44,0.38,1592.0,2000881.0
65,PETR4,2022-07-15,PETRG309,CALL,A,OTM,31.94,0.04,774.0,252630.0
77,PETR4,2022-07-15,PETRG331,CALL,A,OTM,31.44,0.06,2778.0,1032851.0
85,PETR4,2022-07-15,PETRG345,CALL,A,ATM,27.94,1.07,962.0,2503017.0
86,PETR4,2022-07-15,PETRG349,CALL,E,OTM,29.69,0.30,736.0,773619.0
87,PETR4,2022-07-15,PETRG350,CALL,A,ATM,28.44,0.81,1399.0,4585958.0
88,PETR4,2022-07-15,PETRG354,CALL,A,ATM,28.94,0.56,1285.0,3434678.0
94,PETR4,2022-07-15,PETRG369,CALL,A,OTM,30.44,0.15,1335.0,1622233.0
95,PETR4,2022-07-15,PETRG374,CALL,A,OTM,30.94,0.09,3239.0,1619785.0
101,PETR4,2022-07-15,PETRG396,CALL,A,OTM,29.94,0.23,1557.0,3580026.0
162,PETR4,2022-07-15,PETRS234,PUT,E,OTM,26.69,0.20,5102.0,2014402.0
163,PETR4,2022-07-15,PETRS237,PUT,E,OTM,24.69,0.07,4595.0,558869.0
171,PETR4,2022-07-15,PETRS262,PUT,E,ATM,28.19,0.63,847.0,1618664.0
206,PETR4,2022-07-15,PETRS335,PUT,E,OTM,26.94,0.25,838.0,975237.0
212,PETR4,2022-07-15,PETRS345,PUT,E,ATM,27.94,0.49,2400.0,2660520.0

In [ ]:
aux[(aux['Vencimento'] == '2022-07-15') & (aux['Tipo'] == 'PUT') & (aux['Preço'] < 0.05)]

,ativo_obj,Vencimento,Ticker,Tipo,Modelo,A/I/OTM,Strike,Preço,N. de negócios,Volume Neg.
127,PETR4,2022-07-15,PETRS1,PUT,E,OTM,13.44,0.01,3.0,4.0
128,PETR4,2022-07-15,PETRS2,PUT,E,OTM,13.94,0.01,11.0,390.0
129,PETR4,2022-07-15,PETRS3,PUT,E,OTM,14.44,0.01,1.0,10.0
130,PETR4,2022-07-15,PETRS4,PUT,E,OTM,15.44,0.01,1.0,10.0
131,PETR4,2022-07-15,PETRS5,PUT,E,OTM,18.44,0.01,1.0,5.0
132,PETR4,2022-07-15,PETRS15,PUT,E,OTM,15.19,0.01,1.0,10.0
133,PETR4,2022-07-15,PETRS21,PUT,E,OTM,9.94,0.01,2.0,20.0
134,PETR4,2022-07-15,PETRS22,PUT,E,OTM,10.94,0.01,1.0,20.0
135,PETR4,2022-07-15,PETRS23,PUT,E,OTM,12.44,0.01,1.0,100.0
136,PETR4,2022-07-15,PETRS24,PUT,E,OTM,11.94,0.01,3.0,167.0
137,PETR4,2022-07-15,PETRS25,PUT,E,OTM,12.94,0.01,1.0,10.0
138,PETR4,2022-07-15,PETRS26,PUT,E,OTM,14.94,0.01,1.0,1.0
139,PETR4,2022-07-15,PETRS27,PUT,E,OTM,15.94,0.01,2.0,160.0
140,PETR4,2022-07-15,PETRS28,PUT,E,OTM,16.94,0.01,1.0,5.0
141,PETR4,2022-07-15,PETRS29,PUT,E,OTM,17.94,0.01,1.0,1.0
142,PETR4,2022-07-15,PETRS30,PUT,E,OTM,18.94,0.01,1.0,1.0
143,PETR4,2022-07-15,PETRS94,PUT,E,OTM,18.69,0.01,1.0,1.0
144,PETR4,2022-07-15,PETRS95,PUT,E,OTM,16.19,0.01,1.0,10.0
145,PETR4,2022-07-15,PETRS117,PUT,E,OTM,14.69,0.01,1.0,10.0
146,PETR4,2022-07-15,PETRS121,PUT,E,OTM,19.19,0.01,1.0,1.0
147,PETR4,2022-07-15,PETRS130,PUT,E,OTM,15.69,0.01,1.0,10.0
148,PETR4,2022-07-15,PETRS137,PUT,E,OTM,16.69,0.01,1.0,5.0
149,PETR4,2022-07-15,PETRS140,PUT,E,OTM,17.69,0.01,1.0,9.0
150,PETR4,2022-07-15,PETRS152,PUT,E,OTM,17.19,0.01,1.0,1.0
151,PETR4,2022-07-15,PETRS156,PUT,E,OTM,18.19,0.01,1.0,5.0
152,PETR4,2022-07-15,PETRS178,PUT,E,OTM,20.19,0.01,37.0,856.0
153,PETR4,2022-07-15,PETRS184,PUT,E,OTM,19.69,0.01,4.0,22.0
154,PETR4,2022-07-15,PETRS194,PUT,E,OTM,20.69,0.01,54.0,7887.0
155,PETR4,2022-07-15,PETRS202,PUT,E,OTM,8.94,0.01,1.0,3.0
156,PETR4,2022-07-15,PETRS209,PUT,E,OTM,23.19,0.04,47.0,5766.0
157,PETR4,2022-07-15,PETRS216,PUT,E,OTM,10.44,0.01,1.0,3.0
159,PETR4,2022-07-15,PETRS221,PUT,E,OTM,22.69,0.03,71.0,1674.0
161,PETR4,2022-07-15,PETRS226,PUT,E,OTM,11.44,0.01,1.0,1.0
164,PETR4,2022-07-15,PETRS239,PUT,E,OTM,21.69,0.02,24.0,446.0
166,PETR4,2022-07-15,PETRS243,PUT,E,OTM,22.19,0.03,21.0,1869.0
167,PETR4,2022-07-15,PETRS246,PUT,E,OTM,21.19,0.02,13.0,2189.0
175,PETR4,2022-07-15,PETRS275,PUT,E,OTM,20.94,0.01,20.0,134.0
176,PETR4,2022-07-15,PETRS277,PUT,E,OTM,16.44,0.01,1.0,1.0
177,PETR4,2022-07-15,PETRS285,PUT,E,OTM,21.94,0.02,47.0,4800.0
178,PETR4,2022-07-15,PETRS286,PUT,E,OTM,17.44,0.01,1.0,1.0
179,PETR4,2022-07-15,PETRS290,PUT,E,OTM,22.44,0.03,73.0,6842.0
183,PETR4,2022-07-15,PETRS294,PUT,E,OTM,22.94,0.03,32.0,3242.0
184,PETR4,2022-07-15,PETRS295,PUT,E,OTM,19.94,0.01,22.0,1556.0
186,PETR4,2022-07-15,PETRS299,PUT,E,OTM,23.44,0.04,101.0,10799.0
187,PETR4,2022-07-15,PETRS300,PUT,E,OTM,20.44,0.01,54.0,1995.0
191,PETR4,2022-07-15,PETRS307,PUT,E,OTM,19.44,0.01,2.0,6.0
193,PETR4,2022-07-15,PETRS311,PUT,E,OTM,21.44,0.01,14.0,2342.0